(() => {
  const media = window.LESSON_MEDIA || (window.LESSON_MEDIA = {});

  const VIDEO_LIBRARY = {
    foundation:{id:'mVvQ7cNT8-k',title:'Freelancing for Beginners 2025',channel:'YouTube Bangla - Jahir'},
    practice:{id:'SiODMoo6Dzs',title:'Deliberate Practice & Therapy',channel:'Dr. Chris Hoff'},
    portfolio:{id:'8BnGKswuKRI',title:'My First Graphic Design Portfolio — Client Work + Portfolio Tips',channel:'Shruti Rajput'},
    brand:{id:'qa13iuKa8zA',title:"The Creative's Guide to Personal Branding (Full Playbook)",channel:'Oren Meets World'},
    leadershipBrand:{id:'ioPjfm4wx3I',title:'How to develop your personal leadership brand | Leadership Lounge',channel:'Russell Reynolds Associates'},
    content:{id:'Kq4sAvwUxqg',title:'Personal Branding and Content Creation | Patrick Akil | Beyond Coding Q&A #10',channel:'Beyond Coding'},
    linkedin:{id:'C5qe3u1R1eg',title:'LinkedIn Branding for Marketing Agency Owners',channel:'Social Media Examiner'},
    upwork:{id:'ngzBzH7Ngro',title:'Upwork Tutorial for Beginners',channel:'Learn From Top Rated Freelancer'},
    coldEmail:{id:'a3E7Mcvhbms',title:'How to Write Cold Emails That Get Responses',channel:'Outbound Kitchen'},
    coldValue:{id:'EPgUjZFeVsM',title:"Don't Send A Cold Email Until You Watch This Video",channel:'Outbound Kitchen'},
    sales:{id:'5yXvejaAGYU',title:'5 Ways to Close High-Ticket Sales Consistently',channel:'The Spiritual CEO'},
    scope:{id:'6_kZc8ljz0E',title:'How to Manage Scope Creep in Project Management',channel:'Max Dalton'},
    project:{id:'eFe64U1WVs8',title:'ClickUp Tutorial for Beginners (Step by Step)',channel:'George Vlasyev'},
    pricing:{id:'hgNWEqwkApM',title:'Freelance Pricing Models Explained (retainer, hourly, project)',channel:'Latasha James'},
    invoice:{id:'cM1mIPNRoUg',title:'How To Create an Invoice on FreshBooks (Step-by-Step Tutorial)',channel:'FreshBooks'},
    scam:{id:'2r8PsmVdhbQ',title:'Upwork Scams',channel:'Alec G.'},
    scamWide:{id:'Iyn9D8xnCYI',title:'The Great Freelance Scam | How to Identify Online Scams and Frauds',channel:'Rodrigo Lamadrid - Educación Freelance'},
    budget:{id:'d5EZJBhyWmw',title:'How to Budget on an Irregular Income as a Freelancer',channel:'Do It Myself Peg'},
    upsell:{id:'OwPzheEPQhs',title:'Upselling & Cross-Selling Strategies',channel:'Business of Design'},
    team:{id:'jaVIdBBDCjM',title:'Build a Plug-and-Play Marketing Team Without Hiring Full-Time Staff',channel:'Power Movers'},
    ai:{id:'Rq7gHs4yUDY',title:'Google AI Essentials: Get Essential AI Skills',channel:'Google Career Certificates'},
    burnout:{id:'Dvhu2OK7ffg',title:'How burnout makes us less creative | The Way We Work',channel:'TED'}
  };

  const A = {
    2:['foundation','Use this as a beginner-level companion while you focus on the lesson’s bigger shift from chasing income to becoming a reliable problem solver.',['Notice which beginner expectations need reframing','Separate the desire to earn from the process of becoming useful','Connect professionalism and consistency to long-term results']],
    3:['portfolio','Watch how work is presented to a client, then translate the lesson’s Skill → Service → Deliverable → Value model into language a buyer can understand.',['Notice how raw skills become visible work','Identify the deliverable a client can actually evaluate','Ask what business or communication value the work creates']],
    4:['foundation','Use the basic freelancing examples to practice spotting whether a client already understands the problem or still needs diagnosis before a solution is offered.',['Listen for explicit client needs','Notice where assumptions could replace discovery','Separate “I can do this” from “I understand what is wrong”']],
    5:['foundation','Watch with a market lens: not every problem is equally valuable. Look for signs of demand, urgency, buyer intent and repeat need.',['Identify problems people actively pay to solve','Notice which services connect to clear outcomes','Compare interesting problems with commercially useful problems']],
    6:['foundation','Use this companion as a reality check while turning the lesson’s 90-day Build → Prove → Test roadmap into your own starting plan.',['Identify the first skill-building step','Notice when proof should come before outreach','Turn general advice into one weekly operating routine']],

    7:['practice','This lesson is about choosing a skill strategically; deliberate-practice principles help you judge whether a skill can be improved through focused repetition and feedback.',['Look for the difference between repetition and deliberate practice','Notice why feedback accelerates skill growth','Ask whether your chosen skill gives you clear practice targets']],
    8:['practice','Pair the lesson’s practice system with the video’s deliberate-practice ideas so your learning sessions target weaknesses instead of repeating comfortable tasks.',['Define one specific gap before practicing','Build a feedback step into every session','Track improvement rather than hours alone']],
    9:['portfolio','Use the portfolio examples to see how a capability becomes a client-facing service with a clear output, context and reason to buy.',['Identify the service behind each finished piece','Notice how presentation adds context to deliverables','Translate technical ability into buyer-friendly language']],
    10:['brand','A niche should sharpen recognition without trapping you. Watch how positioning and repeated themes make a personal brand easier to understand.',['Notice how a clear point of view creates recognition','Identify repeatable themes without over-specializing','Separate niche clarity from permanent limitation']],
    11:['portfolio','Study how projects are selected and presented, then compare that presentation with the lesson’s Portfolio Trust Stack.',['How relevance beats a random gallery','Where context and process strengthen credibility','How presentation helps a buyer imagine working with you']],
    12:['portfolio','Treat each portfolio project as a story. Watch for the context, decisions and outcomes that can be turned into a stronger case study.',['Identify the situation before the final work','Notice where process and reasoning can be explained','Capture outcomes and learning instead of showing visuals alone']],
    13:['leadershipBrand','Use the branding framework to sharpen who you help, what you are known for and which repeated signals make your positioning believable.',['Look for clarity, congruence and consistency','Notice why differentiation needs evidence','Choose topics that reinforce the position you want to own']],

    14:['leadershipBrand','A professional freelancer profile is a compact trust signal. Watch how a clear leadership brand communicates expertise before a conversation begins.',['Notice how clarity reduces ambiguity','Identify which proof supports the stated position','Compare personal detail with professionally useful detail']],
    15:['brand','Use the full playbook as a companion to the lesson’s Promise → Proof → Voice → Consistency → Reputation system.',['How a point of view becomes recognizable','How content pillars reinforce a brand promise','Why repetition builds familiarity and trust']],
    16:['linkedin','Use LinkedIn as a case study for platform selection: the right platform is where your buyers, content format and relationship style can work together.',['Notice why audience presence matters more than hype','Compare profile, content and engagement roles','Estimate the consistency cost of maintaining a platform']],
    17:['content','Watch how personal brand and content connect, then turn the ideas into a freelancer content system focused on relevance and trust.',['Identify content that demonstrates expertise','Separate useful content from generic visibility','Notice how repeated topics attract the right conversations']],
    18:['content','Consistency works when the system is sustainable. Watch for ways creators turn ideas into repeatable publishing habits rather than relying on motivation.',['Look for repeatable content formats','Notice how feedback informs the next piece','Choose a publishing rhythm you can sustain']],
    19:['linkedin','Use this to see how topic choice, profile language, engagement and repeated audience signals help a platform understand what you are about.',['Notice repeated niche signals across profile and content','Watch how engagement reinforces positioning','Distinguish algorithm chasing from consistent relevance']],
    20:['leadershipBrand','Trust starts before the first message. Watch how clarity and consistency make a professional identity easier for others to believe.',['Identify trust signals visible before a call','Notice why consistency compounds reputation','Choose what evidence should appear on your public profile']],

    21:['coldValue','Ideal-client thinking makes outreach more relevant. Watch how value-first messaging depends on understanding the recipient rather than sending the same pitch to everyone.',['Identify what makes a prospect worth contacting','Notice how research changes the opener','Connect a real business problem to a relevant offer']],
    22:['upwork','Use Upwork as one concrete client source while the lesson helps you build a broader acquisition map across marketplaces, network, content, outreach and referrals.',['Notice where marketplace demand is visible','Compare marketplace discovery with direct outreach','Avoid depending on one acquisition channel']],
    23:['upwork','Use this walkthrough for platform context while relying on the lesson for durable profile, proposal, conversation and contract principles.',['How profiles and proposals connect','Where beginners lose relevance','Which interface or policy details should be re-verified']],
    24:['linkedin','Professional networking is not collecting contacts. Watch how useful participation, profile clarity and consistent engagement create relationship momentum.',['Notice how to engage before asking for anything','Identify low-pressure relationship-building actions','See how profile credibility supports networking']],
    25:['content','Organic acquisition happens when useful content repeatedly reaches the right people and lowers trust barriers before they contact you.',['Identify content that can trigger buyer questions','Notice how authority compounds through consistency','Connect content to a simple inbound next step']],
    26:['coldEmail','Lead qualification should happen before the message. Watch how specificity and research improve the odds that outreach reaches a relevant prospect.',['Notice what information makes an email specific','Identify signs that the prospect has a real need','Avoid wasting volume on poorly matched leads']],
    27:['coldEmail','Compare the lesson’s Research → Relevant Opener → Useful Observation → Low-Pressure CTA sequence with the video’s response-focused cold-email approach.',['How the message centers the prospect','How specificity creates relevance','How the CTA lowers friction']],
    28:['linkedin','Referrals grow from relationships that remain useful after delivery. Watch how ongoing professional presence supports warm introductions and network trust.',['Notice how value can be given before an ask','Identify natural moments to reconnect','Treat referrals as relationship outcomes, not entitlement']],
    29:['coldValue','Use the video to strengthen the human side of your lead system, then place each outreach attempt inside a trackable Prospect → Contacted → Replied → Call → Proposal pipeline.',['Keep relevance even when outreach becomes systematic','Define a low-pressure next step','Track follow-up without becoming spammy']],

    30:['coldValue','Your first client message should create relevance, not pressure. Watch how a value-first opener earns attention before an offer is pushed.',['Notice the role of context in the opening line','Avoid making the first message about yourself','Use one clear and easy next step']],
    31:['sales','Discovery is where selling becomes diagnosis. Watch how strong sales conversations uncover the real buying problem before trying to close.',['Listen for questions that expose motivation','Separate surface requests from deeper outcomes','Notice when qualification should happen before pitching']],
    32:['sales','Better questions reduce guessing. Use the sales examples to study how questions reveal context, impact, urgency and decision criteria.',['Move from factual questions to impact questions','Listen for buying constraints instead of assuming them','Use answers to shape—not merely decorate—the proposal']],
    33:['scope','The scope box becomes valuable when new requests arrive. Watch how scope creep is identified and turned into a clear change conversation.',['Compare new requests with the written scope','Notice why impact on time and cost must be stated','Use change control instead of emotional refusal']],
    34:['coldEmail','A proposal is a continuation of relevance. Watch how prospect-focused messaging earns attention, then compare it with the lesson’s context → approach → scope → price structure.',['Open with the client’s situation rather than biography','Show that your approach follows from the problem','Make the next step unmistakably clear']],
    35:['pricing','Use this freelancer-focused pricing breakdown to compare hourly, project and retainer thinking before you choose a model for a specific engagement.',['Understand what each pricing model is actually selling','Match model choice to scope and uncertainty','Avoid choosing a model only because it feels familiar']],
    36:['sales','Negotiation is structured trade-off, not automatic discounting. Watch how stronger sales conversations protect value while still moving toward agreement.',['Listen for constraint discovery before concessions','Trade scope, speed or terms instead of giving value away','Know when a poor-fit deal should stay unclosed']],
    37:['sales','Objections often contain missing information. Watch how a sales conversation clarifies hesitation before responding with evidence or options.',['Do not answer an objection you have not understood','Validate the concern without surrendering your position','Use proof or options that match the actual doubt']],
    38:['sales','Closing should confirm fit, scope, price, terms and start conditions—not pressure a doubtful buyer into saying yes.',['Notice the difference between persuasion and qualification','Confirm decision readiness before asking for commitment','Treat a clean “no” as better than a risky “yes”']],

    39:['project','Use the project-management walkthrough to visualize how onboarding information becomes organized tasks, ownership, dates and communication expectations.',['Turn kickoff decisions into visible tasks','Centralize assets and responsibilities','Make the client’s next step easy to understand']],
    40:['project','Focus less on the specific software and more on how tasks, milestones, deadlines and views make a project observable and manageable.',['Break work into trackable units','Make deadlines and ownership visible','Reduce dependence on memory with a shared system']],
    41:['project','A project tool can support communication rhythm when updates, decisions, due dates and risks are visible instead of scattered across messages.',['Create predictable update points','Log decisions that affect delivery','Surface risks before the deadline becomes a surprise']],
    42:['scope','This is the direct companion for the lesson’s scope-creep decision tree: compare every new request with the agreement, then clarify its impact.',['Identify the exact moment scope changes','Explain time/cost impact without blame','Document the approved change before doing extra work']],
    43:['project','Use the task-system ideas to create visible quality-control gates before handoff rather than checking everything from memory at the end.',['Turn requirements into a QA checklist','Add review points before final delivery','Separate “finished” from “verified”']],
    44:['project','Professional handoff is a project phase of its own. Watch how organized tasks and documentation can make files, access, instructions and next steps easier to transfer.',['Plan handoff before the final day','Keep access and documentation organized','Make ownership of post-delivery steps clear']],
    45:['portfolio','A completed project can become proof. Watch how client work is presented, then capture testimonial, context, process and result while details are still fresh.',['Turn finished work into credible evidence','Ask permission before publishing confidential material','Capture the story behind the deliverable']],
    46:['upsell','The examples come from a specific service industry, but the transferable principle is useful: look for the next genuine client need instead of forcing unrelated add-ons.',['Spot adjacent needs created by the original project','Recommend only what improves the client outcome','Let repeat work grow from trust, not pressure']],

    47:['pricing','This freelancer-focused comparison directly supports fixed-price, hourly and recurring pricing decisions; use it to understand trade-offs rather than search for one universal “best” model.',['Compare the incentives of hourly and project pricing','Notice where retainers fit recurring needs','Choose pricing based on scope, risk and client context']],
    48:['invoice','Use this practical invoice walkthrough to see how payment terms, due dates, reminders and professional billing turn an agreement into an operational payment process.',['Include clear payment terms and due dates','Notice how reminders reduce manual chasing','Separate invoicing mechanics from the commercial agreement']],
    49:['scam','Payment safety begins before work starts. Use these scam examples to strengthen your deposit, milestone, identity-check and stop-work rules.',['Spot suspicious payment or identity behavior early','Keep transactions and evidence inside trusted systems when appropriate','Do not let urgency override verification']],
    50:['scope','Written boundaries are what make scope, revisions, communication and change requests manageable. Use the scope-creep examples as practical contract-thinking practice.',['Define what is included and excluded','Document the process for changes','Remember that legal enforceability varies by jurisdiction and should be verified locally']],
    51:['budget','Use the irregular-income budgeting example to connect revenue with reserves, business costs, owner pay, tax planning and reinvestment.',['Separate gross revenue from spendable personal income','Create categories before money arrives','Review actual cash flow rather than relying on one strong month']],
    52:['budget','This is a direct companion for irregular freelance income: build a baseline, reserve and decision rules for low, normal and strong months.',['Calculate a realistic monthly baseline','Use strong months to strengthen the buffer','Avoid expanding fixed expenses after temporary income spikes']],
    53:['scamWide','Use this wider freelance-scam discussion to practice risk recognition across identity, payment, files, platform rules, urgency and pressure.',['Notice social-engineering pressure patterns','Verify identity, payment and files before acting','Exit situations that require you to ignore normal safety controls']],

    54:['upsell','Client retention improves when you keep noticing useful next steps after delivery. Use the cross-sell examples for the principle, not the industry-specific tactics.',['Review results before proposing more work','Connect the next service to a real recurring need','Make staying with you easier than restarting with someone new']],
    55:['pricing','Retainers work when recurring need and defined capacity meet. Watch the retainer section with the lesson’s monthly delivery → review → renew cycle in mind.',['Define what the retainer includes and does not include','Match recurring fees to recurring value or capacity','Review and renew instead of assuming the arrangement runs forever']],
    56:['upsell','Use these cross-sell examples to study value expansion: begin with the core service, identify an adjacent need and offer the next useful layer without manufacturing demand.',['Listen for the client problem behind an add-on','Explain how the additional service changes the outcome','Protect trust by avoiding unnecessary upsells']],
    57:['leadershipBrand','Higher-value specialization depends on being known for a narrower, more important problem. Watch how differentiation and consistent expertise build premium trust.',['Clarify the problem you want to be associated with','Build congruence between message and proof','Let specialization emerge from repeated evidence']],
    58:['leadershipBrand','Authority is accumulated recognition, not a title. Use the branding framework to connect expertise, useful content, proof, conversations and reputation.',['Choose themes you can speak about repeatedly','Make evidence visible alongside opinions','Expect authority to compound over time rather than instantly']],
    59:['team','Use the team-building discussion to see why templates, SOPs, role clarity and repeatable workflows become essential before more people touch the work.',['Document outcomes before delegating tasks','Build repeatable processes before adding complexity','Use systems to reduce dependence on one person’s memory']],
    60:['ai','An official Google companion for practical AI use. Keep the lesson’s Define → Context → Generate → Verify → Edit → Own Decision workflow as the safety rail.',['Use AI to accelerate drafts and routine steps','Verify claims, calculations and client-specific facts','Keep human responsibility for judgment and final delivery']],
    61:['team','Outsourcing works when the collaborator receives a clear outcome, brief, checkpoint and quality standard—not when vague work is simply thrown over the wall.',['Define ownership before assigning work','Create checkpoints that catch problems early','Keep final quality accountability with the person promising the result']],
    62:['team','Use this flexible-team discussion to study the shift from solo delivery toward roles, collaborators, management systems and a repeatable agency offer.',['Notice what must be standardized before scaling','Separate specialist delivery from management responsibility','Grow capacity only when the service and economics can support it']],
    63:['burnout','TED’s burnout discussion reinforces why sustainable performance cannot be built on nonstop output. Use it with the lesson’s workload, recovery and boundary system.',['Notice how over-optimization can reduce creativity','Treat recovery as part of performance capacity','Design workload and boundaries before exhaustion forces a reset']],
    64:['leadershipBrand','End the course by thinking beyond the next gig. Use the branding framework to connect long-term skills, reputation, direction and the professional identity you want to compound.',['Define what you want to be known for over several years','Keep your public signals consistent with the career you are building','Review direction periodically instead of drifting from project to project']]
  };

  Object.entries(A).forEach(([lessonNo, config]) => {
    const [videoKey, note, watch] = config;
    const base = VIDEO_LIBRARY[videoKey];
    if(!base) return;
    const n = Number(lessonNo);
    if(!media[n]) media[n] = {type:'grid',title:`Lesson ${n} Visual Model`,items:[]};
    media[n].video = {...base,note,watch};
  });
})();