window.LESSON_MEDIA = {
  1:{"type":"flow","title":"Freelancing Value Exchange","items":["Skill","Service","Client problem","Solution","Value","Payment","Trust"]},
  2:{"type":"ladder","title":"Problem-Solver Mindset","items":["Earn money","Get work","Offer service","Solve problems","Create value","Build trust"]},
  3:{"type":"flow","title":"Skill → Service → Client Value","items":["Skill","Task","Service","Deliverable","Client value"]},
  4:{"type":"decision","title":"Known vs Unknown Phase","items":["Client has a problem","Knows what is needed?","Known: match a solution","Unknown: diagnose first"]},
  5:{"type":"matrix","title":"Problem Opportunity Score","items":["Demand","Urgency","Budget","Access","Skill fit","Repeat value"]},
  6:{"type":"timeline","title":"90-Day Freelancing Roadmap","items":["Days 1–30 · Build","Days 31–60 · Prove","Days 61–90 · Test"]},
  7:{"type":"compass","title":"Strategic Skill Selection","items":["Demand","Personal fit","Proof potential","Growth path"]},
  8:{"type":"cycle","title":"Deliberate Practice Loop","items":["Choose gap","Build","Review","Get feedback","Improve","Repeat"]},
  9:{"type":"stack","title":"Service Offer Anatomy","items":["Target client","Problem","Deliverables","Process","Boundaries","Value"]},
  10:{"type":"venn","title":"Niche Without a Box","items":["Market relevance","Skill strength","Buyer access","Room to evolve"]},
  11:{"type":"stack","title":"Portfolio Trust Stack","items":["Relevant work","Clear context","Process","Reasoning","Outcome","Credibility"]},
  12:{"type":"flow","title":"Case Study Story","items":["Situation","Problem","Constraints","Approach","Decision","Outcome","Reflection"]},
  13:{"type":"position","title":"Positioning Map","items":["Who you help","Problem you solve","Why you","Proof","Distinct signal"]},
  14:{"type":"stack","title":"Professional Profile Trust Stack","items":["Clear headline","Relevant proof","Specific service","Credibility","Easy contact"]},
  15:{"type":"orbit","title":"Personal Brand Ecosystem","items":["Promise","Proof","Voice","Consistency","Reputation","Relationships"],"video":{"id":"qa13iuKa8zA","title":"The Creative's Guide to Personal Branding (Full Playbook)","channel":"Oren Meets World","note":"Use this to see how positioning, story and consistent content work together in a practical personal-brand system.","watch":["How the creator defines a clear point of view","How content pillars support recognition","Why repetition builds trust"]}},
  16:{"type":"matrix","title":"Platform Selection Map","items":["Buyer presence","Content fit","Networking","Searchability","Consistency cost"]},
  17:{"type":"funnel","title":"Freelancer Content Funnel","items":["Attention","Relevance","Trust","Conversation","Opportunity"]},
  18:{"type":"cycle","title":"Consistency Engine","items":["Create","Publish","Observe","Learn","Improve","Repeat"]},
  19:{"type":"network","title":"Niche Signal Network","items":["Topics","Keywords","Visual style","Audience","Engagement","Platform learning"]},
  20:{"type":"stack","title":"Trust Before the First Call","items":["Clarity","Proof","Consistency","Social evidence","Professional behavior"]},
  21:{"type":"persona","title":"Ideal Client Snapshot","items":["Business type","Problem","Urgency","Budget context","Decision-maker","Buying trigger"]},
  22:{"type":"map","title":"Client Acquisition Map","items":["Marketplaces","Network","Content","Cold outreach","Referrals","Communities"]},
  23:{"type":"flow","title":"Marketplace Client Journey","items":["Profile","Search","Proposal","Conversation","Contract","Delivery","Review"],"video":{"id":"ngzBzH7Ngro","title":"Upwork Tutorial for Beginners","channel":"Learn From Top Rated Freelancer","note":"A practical marketplace walkthrough. Interface details can change, so use the lesson for durable principles and the video for platform context.","watch":["How profiles and proposals connect","Where beginners commonly lose relevance","Which platform details may need current verification"]}},
  24:{"type":"cycle","title":"Professional Networking Loop","items":["Notice","Engage","Help","Connect","Follow up","Stay useful"]},
  25:{"type":"funnel","title":"Organic Client Acquisition","items":["Useful content","Right audience","Trust","Inbound question","Qualified lead"]},
  26:{"type":"score","title":"Lead Qualification Score","items":["Fit","Need","Urgency","Budget","Authority","Timing"]},
  27:{"type":"sequence","title":"Human Cold Outreach","items":["Research","Relevant opener","Useful observation","Simple offer","Low-pressure CTA","Follow-up"],"video":{"id":"a3E7Mcvhbms","title":"How to Write Cold Emails That Get Responses","channel":"Outbound Kitchen","note":"A value-first outreach walkthrough that complements the lesson's research, relevance and low-pressure CTA framework.","watch":["How the message focuses on the prospect","How specificity creates relevance","How the CTA lowers friction"]}},
  28:{"type":"cycle","title":"Referral Relationship Flywheel","items":["Do good work","Stay in touch","Be useful","Ask naturally","Get introduced","Deliver again"]},
  29:{"type":"pipeline","title":"Lead Generation System","items":["Prospects","Qualified","Contacted","Replied","Call","Proposal","Won / nurture"]},
  30:{"type":"anatomy","title":"First Client Message","items":["Context","Relevance","Clarity","Specific next step","Professional tone"]},
  31:{"type":"funnel","title":"Discovery Conversation","items":["Context","Goals","Problems","Impact","Constraints","Decision"]},
  32:{"type":"ladder","title":"Better Question Ladder","items":["Facts","Context","Why","Impact","Priority","Decision criteria"]},
  33:{"type":"box","title":"Scope Definition Box","items":["Outcome","Deliverables","Timeline","Responsibilities","Revisions","Exclusions"]},
  34:{"type":"stack","title":"Proposal Architecture","items":["Client context","Problem","Approach","Scope","Timeline","Price","Next step"],"video":{"id":"r7bqvG5hEhA","title":"How To Write Freelance Proposal in 2026","channel":"Learn From Top Rated Freelancer","note":"A current proposal walkthrough with marketplace examples. Compare the tactics with the lesson's client-context → approach → scope → price structure.","watch":["How the opening earns attention","How the proposal references the client's problem","How the next step is made clear"]}},
  35:{"type":"balance","title":"Pricing Decision System","items":["Scope","Complexity","Risk","Time","Value context","Market","Confidence"]},
  36:{"type":"balance","title":"Negotiation Balance","items":["Client constraints","Your boundaries","Trade-offs","Options","Agreement"]},
  37:{"type":"map","title":"Objection Response Map","items":["Hear","Clarify","Validate","Respond with evidence","Offer options","Confirm"]},
  38:{"type":"gate","title":"Healthy Closing Check","items":["Fit","Scope clear","Decision-maker","Price agreed","Payment terms","Start conditions"]},
  39:{"type":"flow","title":"Client Onboarding Path","items":["Agreement","Payment","Kickoff","Assets","Access","Timeline","Communication rules"]},
  40:{"type":"timeline","title":"Project Planning Timeline","items":["Kickoff","Research","Milestone 1","Review","Milestone 2","QA","Handoff"],"video":{"id":"eFe64U1WVs8","title":"ClickUp Tutorial for Beginners (Step by Step)","channel":"George Vlasyev","note":"A practical project-management walkthrough. The specific tool is optional; focus on how tasks, views, deadlines and collaboration create visibility.","watch":["How work is broken into trackable units","How deadlines and ownership become visible","How a project system reduces memory dependence"]}},
  41:{"type":"rhythm","title":"Communication Rhythm","items":["Kickoff","Scheduled updates","Risk alerts","Feedback windows","Decision log","Closeout"]},
  42:{"type":"decision","title":"Scope Creep Decision Tree","items":["New request arrives","Inside agreed scope?","Yes: schedule it","No: quote time/cost change"]},
  43:{"type":"gate","title":"Quality Control Gates","items":["Requirements","Accuracy","Consistency","Function","Edge cases","Final review"]},
  44:{"type":"stack","title":"Professional Handoff Package","items":["Final files","Instructions","Access","Version notes","License/usage","Next steps"]},
  45:{"type":"cycle","title":"Proof Capture Flywheel","items":["Deliver","Request feedback","Collect testimonial","Document case","Publish proof","Build trust"]},
  46:{"type":"cycle","title":"Long-Term Client Flywheel","items":["Deliver value","Review results","Spot next need","Propose help","Retain","Refer"]},
  47:{"type":"compare","title":"Pricing Model Comparison","items":["Fixed price","Hourly","Value-based","Best-fit conditions","Risks","Controls"]},
  48:{"type":"timeline","title":"Payment Safety Timeline","items":["Deposit","Milestone","Invoice","Reminder","Due date","Escalation"]},
  49:{"type":"shield","title":"Payment Protection Layers","items":["Written scope","Deposit","Milestones","Proof of delivery","Records","Stop-work rule"]},
  50:{"type":"boundary","title":"Professional Boundary System","items":["Scope","Time","Communication","Access","Confidentiality","Respect"]},
  51:{"type":"flow","title":"Freelance Money Flow","items":["Revenue","Taxes/reserves","Business costs","Owner pay","Profit","Reinvestment"]},
  52:{"type":"buffer","title":"Irregular Income Buffer","items":["Baseline expenses","Reserve","Low month","Normal month","Strong month","Rebalance"]},
  53:{"type":"radar","title":"Freelance Risk Radar","items":["Payment","Identity","Scope","Data","Platform rules","Urgency","Pressure"]},
  54:{"type":"cycle","title":"Client Retention Loop","items":["Deliver","Review","Communicate","Improve","Spot next need","Renew"]},
  55:{"type":"cycle","title":"Retainer Revenue Cycle","items":["Recurring need","Defined capacity","Monthly delivery","Review","Renew"]},
  56:{"type":"ladder","title":"Client Value Expansion Ladder","items":["Core service","Adjacent need","Add-on","Strategic support","Ongoing partnership"]},
  57:{"type":"pyramid","title":"Specialization Pyramid","items":["General skill","Focused service","Specific problem","Deep expertise","Premium trust"]},
  58:{"type":"engine","title":"Authority Engine","items":["Expertise","Useful content","Proof","Conversations","Recognition","Opportunities"]},
  59:{"type":"map","title":"Freelance Operating System","items":["Templates","SOPs","Automation","Tracking","Review","Improvement"]},
  60:{"type":"loop","title":"Human + AI Workflow","items":["Define problem","Give context","Generate","Verify","Edit","Own decision","Deliver"],"video":{"id":"Rq7gHs4yUDY","title":"Google AI Essentials: Get Essential AI Skills","channel":"Google Career Certificates","note":"An official Google overview of practical AI skill-building. Use it alongside the lesson's human-verification and responsibility framework.","watch":["Where AI can speed up routine work","Why human judgment still matters","How to treat AI output as a draft, not authority"]}},
  61:{"type":"lanes","title":"Delegation Workflow","items":["Define outcome","Choose collaborator","Brief","Checkpoint","QA","Deliver","Review"]},
  62:{"type":"org","title":"Freelancer → Agency Transition","items":["Solo delivery","Repeatable system","Collaborators","Roles","Management","Agency offer"]},
  63:{"type":"balance","title":"Sustainable Performance Balance","items":["Workload","Recovery","Boundaries","Focus","Health","Relationships"]},
  64:{"type":"compass","title":"Long-Term Career Compass","items":["Skills","Market","Income model","Reputation","Lifestyle","Learning","Direction"]}
};